def text_cleanup(text):
    dict_name_swaps = {
        '{ron Ore': 'Iron Ore',
        'tron Ore': 'Iron Ore',
        'lron Ore': 'Iron Ore',
        'lron Hide': 'Iron Hide',
        'Wlirefiber': 'Wirefiber',
        'lronwood': 'Ironwood',
        'Iron ingot': 'Iron Ingot',
        'Steel ingot': 'Steel Ingot',
        'Starmetal ingot': 'Starmetal Ingot',
        'Orichalcum ingot': 'Orichalcum Ingot',
        'Cheese Balt': 'Cheese Bait',
        'tron Cartridge': 'Iron Cartridge',
        'Smail Quartz Crystal': 'Small Quartz Crystal',
        'Powertul Focus Potion': 'Powerful Focus Potion',
        'iron Ore': 'Iron Ore',
        'fron Ore': 'Iron Ore',
        'Cut Flawed Camelian': 'Cut Flawed Carnelian',
        '{ron ingot': 'Iron Ingot',
        '{ron Ingot': 'Iron Ingot',
        'Sliver Ingot': 'Silver Ingot',
        'Silver ingot': 'Silver Ingot',
        'Gold ingot': 'Gold Ingot',
        '{ron Hide': 'Iron Hide',
        'tron Hide': 'Iron Hide',
        'Goid Ore': 'Gold Ore',
        'Fae tron': 'Fae Iron',
        'Shadowtur': 'Shadowfur',
        'Voldmetal': 'Voidmetal',
        'Quilibark': 'Quillbark',
        'Scalecioth': 'Scalecloth',
        'Vold Essence': 'Void Essence',
        'Dlamond': 'Diamond',
        'Voldbent ingot': 'Voidbent Ingot',
        'Julcy Ham Hock': 'Juicy Ham Hock',
        'Dili': 'Dill',
        'Juicy Hock': 'Juicy Ham Hock',
        'Dil': 'Dill',
        'Fish Oll': 'Fish Oil',
        'Broccoll': 'Broccoli',
        'Pouttry Thigh': 'Poultry Thigh',
        'Medium Electric Ee!': 'Medium Electric Eel',
        'Smail Catfish': 'Small Catfish',
        'Smail Piranha': 'Small Piranha',
        'Firm Fish Fliet': 'Firm Fish Filet',
        'Biue-blooded Barb': 'Blue-blooded Barb',
        'Biue-Winged Serpe': 'Blue-Winged Serpe',
        '‘Small Quartz Crystal': 'Small Quartz Crystal',
        'tron Pocketwatch': 'Iron Pocketwatch',
        'Stiver of Crystal': 'Sliver of Crystal',
        'tron Hook': 'Iron Hook',
        'iron Hook': 'Iron Hook',
        'Stee! Lumberjack\'s Charm': 'Steel Lumberjack\'s Charm',
        'Stee! Jewelcrafter\'s Charm': 'Steel Jewelcrafter\'s Charm',
        'Reinforced Stee! Great Axe Charm': 'Reinforced Steel Great Axe Charm',
        'Antmal Claw': 'Animal Claw',
        'Oried Dryad Sap': 'Dried Dryad Sap',
        'Orichaloum Shield Charm': 'Orichalcum Shield Charm',
        'Orichaicum Shield Charm': 'Orichalcum Shield Charm',
        'Orichaicum Engineer\'s Charm': 'Orichalcum Engineer\'s Charm',
        'Shard Baetylus': 'Shard of Baetylus',
        'Silver of Sparkmetal': 'Sliver of Sparkmetal',
        'fron Hook': 'Iron Hook',
        'Reinforced Stee! Musket Charm': 'Reinforced Steel Musket Charm',
        'Riveted Orlchalcum Mail': 'Riveted Orichalcum Mail',
        'Reinforced Starmeta! Rapier Charm': 'Reinforced Starmetal Rapier Charm',
        'Anima! Claw': 'Animal Claw',
        'Silver of Baetylus': 'Sliver of Baetylus',
        'Stee! Miner\'s Charm': 'Steel Miner\'s Charm',
        'Drop of Azoth Oll': 'Drop of Azoth Oil',
        'Silver of Thunderstone': 'Sliver of Thunderstone',
        'Steel Vold Gauntlet Charm': 'Steel Void Gauntlet Charm',
        'Wlreweave': 'Wireweave',
        'Shelidust Flux': 'Shelldust Flux',
        'Timeless Void Gauntiet Shard': 'Timeless Void Gauntlet Shard',
        'Powertul Alkahest': 'Powerful Alkahest',
        'Vold Pitcher': 'Void Pitcher',
        'Lifebloom Leat': 'Lifebloom Leaf',
        'Shelibed Cap': 'Shellbed Cap',
        'Polson Sac': 'Poison Sac',
        'Madtom Toxins.': 'Madtom Toxins',
        'Frult Salad with Toasted Coconut': 'Fruit Salad with Toasted Coconut',
        'Short Barre! Countertop': 'Short Barrel Countertop',
        'Shadecioth': 'Shadecloth',
        'Filnt': 'Flint',
        'Brilllant Aquamarine': 'Brilliant Aquamarine',
        'Vold Ore': 'Void Ore',
        'Voldbent tngot': 'Voidbent Ingot',
        'Voidbent ingot': 'Voidbent Ingot',
        'Gold tngot': 'Gold Ingot',
        'Platinum ingot': 'Platinum Ingot',
        'Orichaicum Ingot': 'Orichalcum Ingot',
        'Cut Brilliant Camelian': 'Cut Brilliant Carnelian',
        'Phoenlxweave': 'Phoenixweave',
        'Smail Electric Eel': 'Small Electric Eel',
        'Dilt': 'Dill',
        'Smail Animal Bone': 'Small Animal Bone',
        '{ron Hook': 'Iron Hook',
        'Shard Crystalized Ectoplasm': 'Shard of Crystalized Ectoplasm',
        'Oryad Bark': 'Dryad Bark',
        'ron Hide': 'Iron Hide',
        'Reinforced Stee! Bow Charm': 'Reinforced Steel Bow Charm',
        'iron Guardsman\'s Insignia': 'Iron Guardsman\'s Insignia',
        'Drop of Quicksliver': 'Drop of Quicksilver',
        'Large Elk Hoot': 'Large Elk Hoof',
        'Shard of Crystallzed Azoth': 'Shard of Crystalized Azoth',
        'Reinforced Stee! War Hammer Charm': 'Reinforced Steel War Hammer Charm',
        'Britliant Animus': 'Brilliant Animus',
        'Vold Crystal Core': 'Void Crystal Core',
        'Biueberry': 'Blueberry',
        'Mushroom Fins.': 'Mushroom Fins',
        'fron Hide': 'Iron Hide',
        'Blightroot Leat': 'Blightroot Leaf',
        'Piatinum Ore': 'Platinum Ore',
        'oil': 'Oil',
        'Silver of Cobalt': 'Sliver of Cobalt',
        'Bumbieblossom': 'Bumbleblossom',
        'Bilghtroot Leaf': 'Blightroot Leaf',
        'Fllnt Arrow': 'Flint Arrow',
        'Sliver ingot': 'Silver Ingot',
        'Piatinum Ingot': 'Platinum Ingot',
        'Buirush Cob': 'Bulrush Cob',
        'Lightning Beetie': 'Lightning Beetle',
        'Orichaicum Ore': 'Orichalcum Ore',
        'Btisterweave': 'Blisterweave',
        'Biisterweave': 'Blisterweave',
        'Brilllant Moonstone': 'Brilliant Moonstone',
        'Brilllant Pearl': 'Brilliant Pearl',
        'Brilllant Malachite': 'Brilliant Malachite',
        'Flutty Stuffing': 'Fluffy Stuffing',
        'Pristine Emeraid': 'Pristine Emerald',
        'Schematic: Shattersiash': 'Schematic: Shatterslash',
        '(ron Hide': 'Iron Hide',
        'Wiretiber': 'Wirefiber',
        'Schematic: Frost Falry\'s Gift': 'Schematic: Frost Fairy\'s Gift',
        'Brilllant Amethyst': 'Brilliant Amethyst',
        'Britliant Jasper': 'Brilliant Jasper',
        'Fiawed Ruby': 'Flawed Ruby',
        'Brilllant Sapphire': 'Brilliant Sapphire',
        'Brilllant Amber': 'Brilliant Amber',
        'Brilllant Carnelian': 'Brilliant Carnelian',
        'Ectopiasmic Essence': 'Ectoplasmic Essence',
        'Voldbent Ingot': 'Voidbent Ingot',
        'fell]': 'Oil',
        'fell}': 'Oil',
        'Fiawed Topaz': 'Flawed Topaz',
        'Fiawed Opal': 'Flawed Opal',
        'Fiawed Jasper': 'Flawed Jasper',
        'Briiliant Amethyst': 'Brilliant Amethyst',
        'Pristine Bear Ciaw': 'Pristine Bear Claw',
        '"Bear in Meadow” Painting': '"Bear in Meadow" Painting',
        '"Flying Dutchman” Painting': '"Flying Dutchman" Painting',
        '"Journey\'s End” Painting': '"Journey\'s End" Painting',
        '"Spring River” Painting': '"Spring River" Painting',
        'Goid ingot': 'Gold Ingot',
        'Obsidian Voldstone': 'Obsidian Voidstone',
        'Cut Pristine Camelian': 'Cut Pristine Carnelian',
        'Linen Arcane Embroldery': 'Linen Arcane Embroidery',
        'Fancy Sheil': 'Fancy Shell',
        'Fancy Shet!': 'Fancy Shell',
        'Timetess Tower Shield Shard': 'Timeless Tower Shield Shard',
        'Timetess Rapier Shard': 'Timeless Rapier Shard',
        'Timetess Hatchet Shard': 'Timeless Hatchet Shard',
        'Timeless Gauntiets Shard': 'Timeless Gauntlets Shard',
        'Timetess Legguards Shard': 'Timeless Legguards Shard',
        'Nightcrawier Balt': 'Nightcrawler Bait',
        'Powertul Health Potion': 'Powerful Health Potion',
        'Bolled Cabbage': 'Boiled Cabbage',
        'Standard Repalr Kit': 'Standard Repair Kit',
        'Strong incense': 'Strong Incense',
        'Steel tngot': 'Steel Ingot',
        'Cut Carnetian': 'Cut Carnelian',
        'Cut Brilllant Ruby': 'Cut Brilliant Ruby',
        'Cut Brilllant Amethyst': 'Cut Brilliant Amethyst',
        'Cut Brillant Carnelian': 'Cut Brilliant Carnelian',
        'Fiawed Amethyst': 'Flawed Amethyst',
        'Fiawed Onyx': 'Flawed Onyx',
        'Brillant Opal': 'Brilliant Opal',
        'Brillant Amethyst': 'Brilliant Amethyst',
        'Brillant Jasper': 'Brilliant Jasper',
        'Brillant Topaz': 'Brilliant Topaz',
        'Brillant Ruby': 'Brilliant Ruby',
        'Surveyor\'’s Tools': 'Surveyor\'s Tools',
        'Tolviurn': 'Tolvium',
        'Bilsterweave': 'Blisterweave',
        'Ciam Bait': 'Clam Bait',
        'Woodiouse Bait': 'Woodlouse Bait',
        'Animai Horn': 'Animal Horn',
        'ron Guardsman\'s Insignia': 'Iron Guardsman\'s Insignia',
        'Smail Elk Hoof': 'Small Elk Hoof',
        'Huge Elk Hoot': 'Huge Elk Hoof',
        'Orichalcum Void Gauntiet Charm': 'Orichalcum Void Gauntlet Charm',
        'fell': 'Oil',
        'oll': 'Oil',
        'ron Ore': 'Iron Ore',
        'Petaicap': 'Petalcap',
        'Piatecap Flesh': 'Platecap Flesh',
        'felll': 'Oil',
        'Light Meat': 'Light Meal',
        'Light Meai': 'Light Meal',
        'Electric Eel Balt': 'Electric Eel Bait',
        'Roasted Vegetable Mediey': 'Roasted Vegetable Medley',
        'lron Ingot': 'Iron Ingot',
        'Cooking Oll': 'Cooking Oil',
        'Reinforced Stee Rapier Charm': 'Reinforced Steel Rapier Charm',
        'Timeless Ice Gauntiet Shard': 'Timeless Ice Gauntlet Shard',
        'Timeless Rapter Shard': 'Timeless Rapier Shard',
        'Timeless Vold Gauntlet Shard': 'Timeless Void Gauntlet Shard',
        'Bread Balt': 'Bread Bait',
        'Firefly Balt': 'Firefly Bait',
        'Woodilouse Bait': 'Woodlouse Bait',
        'Powertul Corrupted Ward Potion': 'Powerful Corrupted Ward Potion',
        'Fish Balt': 'Fish Bait',
        'Powertul Incense': 'Powerful Incense',
        'Biessed Scepter': 'Blessed Scepter',
        'lron ingot': 'Iron Ingot',
        'Steet Ingot': 'Steel Ingot',
        'Piatinum ingot': 'Platinum Ingot',
        'Cut Brillant Jasper': 'Cut Brilliant Jasper',
        'Orichatcum Ingot': 'Orichalcum Ingot',
        'Satisfying Meai': 'Satisfying Meal',
        'Filnt Arrow': 'Flint Arrow',
        'Frogfish Tall': 'Frogfish Tail',
        'Nightcrawier Bait': 'Nightcrawler Bait',
        'Recipe: Blueberry Ple': 'Recipe: Blueberry Pie',
        'Recipe: Glazed Meion Bread': 'Recipe: Glazed Melon Bread',
        'Pattern: Holly Regent Headplece': 'Pattern: Holly Regent Headpiece',
        'Alr Mote': 'Air Mote',
        'Alr Essence': 'Air Essence',
        'Phaseflber': 'Phasefiber',
        'Fiawed Sapphire': 'Flawed Sapphire',
        'Fiawed Aquamarine': 'Flawed Aquamarine',
        'Fiawed Moonstone': 'Flawed Moonstone',
        'Olamond': 'Diamond',
        'Brilllant Jasper': 'Brilliant Jasper',
        'Brilllant Topaz': 'Brilliant Topaz',
        'Goid Ingot': 'Gold Ingot',
        'Steet ingot': 'Steel Ingot',
        'lron Hook': 'Iron Hook',
        'Powertul Corruption Tincture': 'Powerful Corruption Tincture',
        'Shadectloth': 'Shadecloth',
        'Fiawed Emerald': 'Flawed Emerald',
        'Britliant Aquamarine': 'Brilliant Aquamarine',
        'Britliant Malachite': 'Brilliant Malachite',
        'Britliant Amethyst': 'Brilliant Amethyst',
        'Britliant Moonstone': 'Brilliant Moonstone',
        'Briiliant Ruby': 'Brilliant Ruby',
        'Britliant Diamond': 'Brilliant Diamond',
        'Precision Armoring Toois': 'Precision Armoring Tools',
        'Cut Brilllant Camelian': 'Cut Brilllant Carnelian',
        'Cut Pristine Onvx': 'Cut Pristine Onyx',
        'Orichalcum Rapler Charm': 'Orichalcum Rapier Charm',
        'Drop of lronwood Sap': 'Drop of Ironwood Sap',
        'Timeless Life Staff Snard': 'Timeless Life Staff Shard',
        'tron Arrow': 'Iron Arrow',
        'Orichaicum Cartridge': 'Orichalcum Cartridge',
        'Schematic: Etemal Dusk': 'Schematic: Eternal Dusk',
        'Pattern: Tip of the iceberg': 'Pattern: Tip of the Iceberg',
        'Quartermasters Notes': 'Quartermaster\'s Notes',
        'Cut Brilllant Aquamarine': 'Cut Brilliant Aquamarine',
        'Cut Brillant Diamond': 'Cut Brilliant Diamond',
        'Fish Oit': 'Fish Oil',
        'Sliver of Crystallized Ectoplasm': 'Sliver of Crystalized Ectoplasm',
        'Pristine Animai Claw': 'Pristine Animal Claw',
        'Sliver of Crystallized Azoth': 'Sliver of Crystalized Azoth',
        'Timeless Void Gaunttet Shard': 'Timeless Void Gauntlet Shard',
        'Giliflower Gills': 'Gillflower Gills',
        'Advanced Repalr Kit': 'Advanced Repair Kit',
        'lron Cartridge': 'Iron Cartridge',
        'Shadeclioth': 'Shadecloth',
        'Brilllant Emerald': 'Brilliant Emerald',
        'Brifliant Onyx': 'Brilliant Onyx',
        'Briiliant Jasper': 'Brilliant Jasper',
        'Pattern: Frostbarret': 'Pattern: Frostbarrel',
        'Brillant Sapphire': 'Brilliant Sapphire',
        'Brillant Malachite': 'Brilliant Malachite',
        'Brillant Amber': 'Brilliant Amber',
        'Brilllant Diamond': 'Brilliant Diamond',
        'Pristine Bear Pett': 'Pristine Bear Pelt',
        'Surveyor\'s Toois': 'Surveyor\'s Tools',
        'Cut Brilllant Malachite': 'Cut Brilliant Malachite',
        'lron Corrupted Casing': 'Iron Corrupted Casing',
        'Stlver of Crystallzed Ectoplasm': 'Sliver of Crystalized Ectoplasm',
        'Viat of Viscous Azoth': 'Vial of Viscous Azoth',
        'Draught of lronwood Sap': 'Draught of Ironwood Sap',
        'Fish with Tarragon and Oregano.': 'Fish with Tarragon and Oregano',
        'Recipe: Squid Ink Pasta with Clams.': 'Recipe: Squid Ink Pasta with Clams',
        'Common Fecus Potion': 'Common Focus Potion',
        'Hearty Meat': 'Hearty Meal',
        'Common Health Potlon': 'Common Health Potion',
        'Recipe: Bear Flank Pinwheels:': 'Recipe: Bear Flank Pinwheels',
        'infused Ancient Ward Potion': 'Infused Ancient Ward Potion',
        'iron Hide': 'Iron Hide',
        'Wlrefiber': 'Wirefiber',
        'Fiawed Pearl': 'Flawed Pearl',
        'lronweod': 'Ironwood',
        'Sealecord': 'Scalecord',
        'Orlchalcum Ore': 'Orichalcum Ore',
        'Bllsterweave': 'Blisterweave',
        'Brilliant Carnellan': 'Brilliant Carnelian',
        'Surveyor\'s Tools:': 'Surveyor\'s Tools',
        'lronweod Planks': 'Ironwood Planks',
        'Fish Fllet': 'Fish Filet',
        'Sllver of Niter': 'Sliver of Niter',
        'iron Battle Medal': 'Iron Battle Medal',
        'Orlchalcum Arcanist\'s Charm': 'Orichalcum Arcanist\'s Charm',
        'Intused Fang': 'Infused Fang',
        'Powerful Proficlency Booster': 'Powerful Proficiency Booster',
        'Schematic: Mapte End Table': 'Schematic: Maple End Table',
        'Schematic: Steet Settler\'s Stove': 'Schematic: Steel Settler\'s Stove',
        'Schematic: Mapte Full Bed': 'Schematic: Maple Full Bed',
        'Dirty Olshes': 'Dirty Dishes',
        'Schematic: Mapte Chest of Drawers': 'Schematic: Maple Chest of Drawers',
        'Ash Dining Chalr': 'Ash Dining Chair',
        'Schematic: Mapte Bar Stool': 'Schematic: Maple Bar Stool',
        'tron Pan': 'Iron Pan',
        'Schematic: Old Log Stoot': 'Schematic: Old Log Stool',
        'lron Cup': 'Iron Cup',
        'tron Wok Set': 'Iron Wok Set',
        'Totvium': 'Tolvium',
        'IronIngot': 'Iron Ingot',
        'SafIron': 'Saffron',
        'Firetox': 'Firefox',
        'Silkwoave': 'Silkweave',
        'Abala Serpe': 'Abaia Serpe',
        'Fish Olt': 'Fish Oil',
        'Crop of Withered Essence': 'Drop of Withered Essence',
        'Tilivix-xeMerel gab loic-tel Letercl lars': 'Infused Corrupted Coating',
        'aiites-xeMatcrel-uul-Veci tien Potion': 'Infused Regeneration Potion',
        'SJoy or-re Mi Core': 'Spiced Nog',
        'fetiivel-1g': 'Ginger',
        'Powerful Corrupted Letercl lars': 'Powerful Corrupted Coating',
        'Powerful Angry Earth LOrer-1ilare': 'Powerful Angry Earth Coating',
        'le-X-F4 ile Melel-t-10at-3': 'Freezing Lodestone',
        'LO7- sr-Je-9': 'Cabbage'





    }
    if text in dict_name_swaps:
        text = dict_name_swaps[text]

    dict_root_swaps = {
        'lron': 'Iron',
        'tron ': 'Iron',
        'Mapte': 'Maple',
        'Stoot': 'Stool',
        'Chalr': 'Chair',
        'Orlchalcum': 'Orichalcum',
        'iron': 'Iron',
        'weod': 'wood',
        'Fiawed': 'Flawed',
        'Sllver': 'Sliver',
        'Potlon': 'Potion',
        'Brillant': 'Brilliant',
        'Britliant': 'Brilliant',
        'Brilllant': 'Brilliant',
        'Alr': 'Air',
        'Steet': 'Steel',
        ' Balt': 'Bait',
        'Smail': 'Small',
        'Camelian': 'Carnelian',
        'Orichaicum': 'Orichalcum',
        'Stee!': 'Steel',
        'Vold': 'Void',
        'Armolre': 'Armoire',
        'Olning': 'Dining',
        'Shelt': 'Shelf',
        'Casuat': 'Casual',
        'Barret': 'Barrel',
        'Chatr': 'Chair',
        'fron': 'Iron',
        'Cratting': 'Crafting',
        'Wildllfe': 'Wildlife',
        'Bim': 'Dim',
        'Orichaloum': 'Orichalcum',
        'Ghest': 'Chest',
        'Palnted': 'Painted',
        'pollshed': 'polished',
        'Chandeller': 'Chandelier',
        'Gombat': 'Combat',
        'Garved': 'Carved',
        'Omate': 'Ornate',
        'Polgnant': 'Poignant',
        'Armchalr': 'Armchair',
        'Hom': 'Horn',
        'Trellls': 'Trellis',
        'Unsettiing': 'Unsettling',
        'Demljohn': 'Demijohn',
        'Qak': 'Oak',
        'Lantem': 'Lantern',
        'Goid': 'Gold',
        'Lite': 'Life',
        'Voild': 'Void',
        'Orlchaleum': 'Orichalcum',
        'Britiiant': 'Brilliant',
        'Brittiant': 'Brilliant',
        'Mercurlal': 'Mercurial',
        'Anclent': 'Ancient',
        'tronwood': 'Ironwood',
        'Logguards': 'Legguards',
        'lce Crystal Core': 'Ice Crystal Core',
        'Leat': 'Leaf',
        'Ledestone': 'Lodestone',
        'Oragon': 'Dragon',
        'Splnefish': 'Spinefish',
        'Gommon': 'Common',
        'Cormupted': 'Corrupted',
        'Bilght': 'Blight',
        'Gabbage': 'Cabbage',
        'Dyo': 'Dye',
        'Splced': 'Spiced',
        'UnsettlIng': 'Unsettling',
        'Patrified': 'Petrified',
        'Oummy': 'Dummy',
        'Potrified': 'Petrified',
        'Leafher': 'Leather',
        'IronIngot': 'Iron Ingot',
        'Charceal': 'Charcoal',
        'Wyrdweood': 'Wyrdwood',
        'Briltiant': 'Brilliant',
        'SafIron': 'Saffron',
        'Gooking': 'Cooking',
        'Peppercom': 'Peppercorn',
        'Cobait': 'Cobalt',
        'Siarmetal': 'Starmetal',
        'Oraught': 'Draught',
        'Crystallzed': 'Crystalized',
        'Sparkmetat': 'Sparkmetal',
        'Crystatized': 'Crystalized',
        'IronBattle': 'Iron Battle',
        'Orop': 'Drop',
        'Briiliant': 'Brilliant',
        'Glump': 'Clump',
        'Gonsecrated': 'Consecrated',
        'Embroldered': 'Embroidered',
        'Broastplate': 'Breastplate',
        'Heim': 'Helm',
        'Timetess': 'Timeless',
        'Tabte': 'Table',
        'Whrefiber': 'Wirefiber',
        'GlIntstrands': 'Glintstrands',
        'Orichatcum': 'Orichalcum',
        'Sealecloth': 'Scalecloth',
        'Emeraid': 'Emerald',
        'Scalectoth': 'Scalecloth',
        'Emeratd': 'Emerald',
        'Bummy': 'Dummy',
        'Petritied': 'Petrified',
        'Steal': 'Steel',
        'Ptatinum': 'Platinum',
        'tronwoed': 'Ironwood',
        'Fitet': 'Filet',
        'Tendertoin': 'Tenderloin',
        'Onlon': 'Onion',
        'Scuipin': 'Sculpin',
        'Brop': 'Drop',
        'Falnt': 'Faint',
        'Ghunk': 'Chunk',
        'Animat': 'Animal',
        'Starmetat': 'Starmetal',
        'Obsidlan': 'Obsidian',
        'Materlal': 'Material',
        'Tait': 'Tail',
        'Antmal': 'Animal',
        'Goating': 'Coating',
        'Heaith': 'Health',
        'Proticlency': 'Proficiency',
        'Repalr': 'Repair',
        'Diamend': 'Diamond',
        'Dlamend': 'Diamond',
        'Brliliant': 'Brlilliant',
        'Wlidwood': 'Wildwood',
        'Polt': 'Pelt',
        'Opat': 'Opal',
        'Phosnixweave': 'Phoenixweave',
        'Snall': 'Snail',
        'Stene': 'Stone',
        'Azatea': 'Azalea',
        'Animai': 'Animal',
        'Woaden': 'Wooden',
        'Wirewoave': 'Wireweave',
        'Scates': 'Scales',
        'Asmodoum': 'Asmodeum',

        # 'imeless': 'Timeless',
        # 'ilkweave': 'Silkweave'

    }

    for i in dict_root_swaps:
        if i in text:
            text = text.replace(i, dict_root_swaps[i])

    return text
